#ifndef GLOBAL_VARIABLES_H
#define GLOBAL_VARIABLES_H

#define SAMPLE_RATE 44100
#define CHANNELS 1
#define BITS_PER_SAMPLE 16
#define DURATION 5
#define BUFFER_SIZE (SAMPLE_RATE * CHANNELS * (BITS_PER_SAMPLE / 8) * DURATION)

#endif // GLOBAL_VARIABLES_H